export const APP_SCREEN = {
    REGISTER_SCREEN: 'REGISTER_SCREEN',
    LOGIN_SCREEN: 'LOGIN_SCREEN',
    HOME_SCREEN: 'HOME_SCREEN'
}

export const ROUTINES_SORTING_CRITERIA = {
    SORT_BY_NAME_INCREASING: 'SORT_BY_NAME_INCREASING',
    SORT_BY_NAME_DECREASING: 'SORT_BY_NAME_DECREASING',
    SORT_BY_CREATED_INCREASING: 'SORT_BY_CREATED_INCREASING',
    SORT_BY_CREATED_DECREASING: 'SORT_BY_CREATED_DECREASING',
    SORT_BY_TIMESTAMP_INCREASING: 'SORT_BY_TIMESTAMP_INCREASING',
    SORT_BY_TIMESTAMP_DECREASING: 'SORT_BY_TIMESTAMP_DECREASING'
}

export const EXERCISES_SORTING_CRITERIA = {
    SORT_BY_NAME_INCREASING: 'SORT_BY_NAME_INCREASING',
    SORT_BY_NAME_DECREASING: 'SORT_BY_NAME_DECREASING',
    SORT_BY_GROUP_INCREASING: 'SORT_BY_GROUP_INCREASING',
    SORT_BY_GROUP_DECREASING: 'SORT_BY_GROUP_DECREASING',
    SORT_BY_REPS_INCREASING: 'SORT_BY_REPS_INCREASING',
    SORT_BY_REPS_DECREASING: 'SORT_BY_REPS_DECREASING'
}