export const APP_SCREEN = {
    REGISTER_SCREEN: 'REGISTER_SCREEN',
    LOGIN_SCREEN: 'LOGIN_SCREEN',
    HOME_SCREEN: 'HOME_SCREEN'
}

export const ROUTINES_SORTING_CRITERIA = {
    SORT_BY_TICKER_INCREASING: 'SORT_BY_TICKER_INCREASING',
    SORT_BY_TICKER_DECREASING: 'SORT_BY_TICKER_DECREASING',
    SORT_BY_TYPE_INCREASING: 'SORT_BY_TYPE_INCREASING',
    SORT_BY_TYPE_DECREASING: 'SORT_BY_TYPE_DECREASING',
    SORT_BY_STRIKE_INCREASING: 'SORT_BY_STRIKE_INCREASING',
    SORT_BY_STRIKE_DECREASING: 'SORT_BY_STRIKE_DECREASING',
    SORT_BY_EXPIRY_INCREASING: 'SORT_BY_EXPIRY_INCREASING',
    SORT_BY_EXPIRY_DECREASING: 'SORT_BY_EXPIRY_DECREASING',
    SORT_BY_SPOT_INCREASING: 'SORT_BY_SPOT_INCREASING',
    SORT_BY_SPOT_DECREASING: 'SORT_BY_SPOT_DECREASING',
    SORT_BY_PREMIUM_INCREASING: 'SORT_BY_PREMIUM_INCREASING',
    SORT_BY_PREMIUM_DECREASING: 'SORT_BY_PREMIUM_DECREASING'
}
